### ISSUE TITLE
Spotify crash when tap "Navigation and other apps" on settings

### ISSUE THREAD

**Issue by Ayden3011** [Natoune/SpotifyMobileLyricsAPI#10]
Hi, first of all, I would like to thank you for the project here. Because of you we have on Spotify Lyrics! 😍🎉

This issue I call on the lyrics-patched version here does not really bother, but only wanted to mention.

If you press your profile on the top left, go into the settings and press "navigation and other apps," then the app crashes directly. 

I don't know if it's up to me, if so I'm sorry. 

Thanks in advance.

**Comment by Natoune** [comment]
Hello. Indeed, the issue occurs on my side as well. I will try to fix this problem. Thank you for your feedback!

**Comment by Ayden3011** [comment]
No problem, thanks for your effort!

**Comment by Natoune** [comment]
This works in the latest version released by xManager (available in the [releases](https://github.com/Natoune/SpotifyMobileLyricsAPI/releases/) section of this repo).

**Comment by KelvinCrag** [comment]
> This works in the latest version released by xManager (available in the [releases](https://github.com/Natoune/SpotifyMobileLyricsAPI/releases/) section of this repo).

This new version breaks podcast
