### ISSUE TITLE
Spotify not allowing me to sign in

### ISSUE THREAD

**Issue by joenuts69** [Natoune/SpotifyMobileLyricsAPI#11]
SInce yesterday, Spotify has been blocking third party sign in, I haven't tried with traditional email and password. It just gives the error "Something went wrong"

**Comment by cyriotic3** [comment]
was about to make a new issue regarding this, having the same problem as well, i believe you can login on version 8.9.18.512 but this specific mode doesn't have the version, i tried the old version but it doesn't work

**Comment by Natoune** [comment]
I made some major changes yesterday, which caused this issue.
It should work again now!

**Comment by cyriotic3** [comment]
> I made some major changes yesterday, which caused this issue. It should work again now!

i tried login in through Facebook and i can confirm it is working now, thanks!
