### ISSUE TITLE
An error occurred while building the patched APK.

### ISSUE THREAD

**Issue by mioscape** [Natoune/SpotifyMobileLyricsAPI#14]
Build it from WSL,

```
./patch_xmanager.sh --server "###" --name "miogang"
Downloading required tools...
No APK provided. Fetching latest patched Spotify release...
Which version of Spotify do you want to patch?
1) Stock
2) Amoled
3) Lite
Enter your choice: 2
Patching Spotify...
Building patched APK...
An error occurred while building the patched APK.
```

**Comment by Natoune** [comment]
Try again with this script and provide the console output
[patch_xmanager.zip](https://github.com/user-attachments/files/17413310/patch_xmanager.zip)

**Comment by mioscape** [comment]
> Try again with this script and provide the console output [patch_xmanager.zip](https://github.com/user-attachments/files/17413310/patch_xmanager.zip)

```
01:01.209 I: [BUILD] Writing files: 7573
01:01.689 I: [BUILD] Writing signature block ...
01:01.777 I: [BUILD] Saved to: patched.apk
./patch_xmanager.sh: line 166: ./build-tools/zipalign: No such file or directoryAn error occurred while building the patched APK.
```

**Comment by Natoune** [comment]
Sorry for the wait, can you provide the full console output with this script?

**Comment by mioscape** [comment]
> Sorry for the wait, can you provide the full console output with this script?

[log.txt](https://github.com/user-attachments/files/17447065/log.txt)

**Comment by Natoune** [comment]
You need to install unzip and it should work: `sudo apt-get install unzip`

**Comment by Natoune** [comment]
This issue is fixed in the [latest commit](https://github.com/Natoune/SpotifyMobileLyricsAPI/commit/6e0de4577cfbcacf4522e89a094789ae4968c696), which uses the `jar` tool to unzip Android build tools instead of `unzip`.
