### ISSUE TITLE
Vercel deploy error 

### ISSUE THREAD

**Issue by joenuts69** [Natoune/SpotifyMobileLyricsAPI#15]
When i try to deploy an instance to Vercel I get an error. 

![image](https://github.com/user-attachments/assets/0a32f618-8345-4a83-91fb-644d2f7d53a8)

**Comment by Natoune** [comment]
This is normal. The `/` endpoint is not used by Spotify, so it's okay if it throws an error. This is also the case for the default server https://lyrics.natanchiodi.fr/.
Try an endpoint like `/color-lyrics/v2/track/4cOdK2wGLETKBW3PvgPWqT` to verify that the server is working.
