### ISSUE TITLE
Lyrics UI

### ISSUE THREAD

**Issue by xC3FFF0E** [Natoune/SpotifyMobileLyricsAPI#2]
<a href="https://ibb.co/rQ2hGzR"><img src="https://i.ibb.co/rQ2hGzR/Screenshot-20240916-152520-2.jpg" alt="Screenshot-20240916-152520-2" border="0" /></a>

Deployed server using Vercel.
Result: Empty lyrics. Tapping on it crashes the app.

**Comment by Natoune** [comment]
This error seems to be related to Vercel returning incorrect headers. I have to work on a patch and I will respond to this issue when it is fixed. You can use the default server that is not hosted on Vercel in the meantime, it should work.

This project is quite new, so it may still be a bit unstable, I apologize for that.

**Comment by Natoune** [comment]
This should work now. Redeploy your server with the latest commit (495e76e) and report back.

**Comment by xC3FFF0E** [comment]
> This should work now. Redeploy your server with the latest commit ([f0e4e8d](https://github.com/Natoune/SpotifyMobileLyricsAPI/commit/f0e4e8d6bf493c3f05b4880c72aa22892fe4924e)) and report back.

Same issue with the lyrics ui.

**Comment by Natoune** [comment]
Try to re-deploy the Vercel server (again), you will need to re-clone this repo for that, and re-patch the apk with the `patch_xmanager.sh`.
If it still doesn't work, I don't know what the problem is.

**Comment by xC3FFF0E** [comment]
**UPDATE:** Working well now, @Natoune. This is an awesome project, and thank you for sharing this with the community. We will add your name as a token of our appreciation to our future releases.
