### ISSUE TITLE
Suggestion: Add few fallback lyrics sources

### ISSUE THREAD

**Issue by Rairof** [Natoune/SpotifyMobileLyricsAPI#4]
I would like to suggest a few fallback source for lyrics if the current used source gets issues or lyrics of any songs aren't available in them. I would probably suggest to look into Netease, LRCLIB etc but as I am not really experienced in this I can't say anything for sure. They might also solve "lyrics not available" issues for others users as they might have connectivity issues with the current sources,  just a thought.

**Comment by Natoune** [comment]
This uses the official Spotify API, it's the best solution and certainly creates less issues than an outside source.
And regarding the unavailable lyrics, it's not that simple. It seems that Spotify first sends an API request that informs it, among other things, whether the lyrics of a song are available or not.
Changing this request would require a bit of reverse engineering and directly modifying the Spotify apk file (patched with xManager) for lyrics that are not natively supported by Spotify.
But it's a good idea and I'll try to implement it, it just might take a bit of time.

**Comment by Rairof** [comment]
https://github.com/Natoune/SpotifyMobileLyricsAPI/issues/4#issuecomment-2362206038
I see, makes sense on how well it works on Spotify considering it's from Spotify. Thank you for your time and development of this API and I'm glad it's available. It's pretty interesting how everything in it works and I'm happy to hear it's not something impossible anymore. Thanks for considering and taking your time in looking into this suggestion. There's no rushing so there's plenty of time to reverse engineer and get things done ❤️👍

**Comment by Natoune** [comment]
I’ve added the providers NetEase and LRCLIB in the last commit as you suggested.

Unfortunately, it’s not possible to properly add lyrics to songs that aren’t available on MusixMatch (the default provider for Spotify), as I had hoped to do.
It is technically possible to force the lyrics box to be displayed (add `const-string p1, "true"` at line 254 of the file `p5c.smali` when decompiling the Spotify APK), but this means that the lyrics box will be shown for all tracks, even instrumental-only ones, which is not the behavior I want.

Regarding the "lyrics not available" issue, this should no longer happen. (Solved in issue #5)

**Comment by Rairof** [comment]
That's great! Thank a lot for your work!

**Comment by hsl1** [comment]
Seems that petitlyrics is also  used  for Japanese musics

**Comment by Rairof** [comment]
@Natoune So far, I have found these music providers, I may add more if I stumble upon anymore of it-
[Deezer](https://deezer.com/)
[LRCLIB](https://lrclib.net/)
[NetEase](https://music.163.com/)
[Megalobiz](https://www.megalobiz.com/)
[Genius](https://genius.com/) (For plain format)
[Lyricsify](https://www.lyricsify.com/)
