### ISSUE TITLE
Voice commands 

### ISSUE THREAD

**Issue by sukabai** [Natoune/SpotifyMobileLyricsAPI#6]
Using:
Lyrics patched AMOLED version
Android 14
MIUI HyperOS latest
Rooted
Android auto AndroidAuto-XLauncherUnlocked-v2.0.1
With xmanager version everything works 
With patched version vocal commands gives error, no matter what artist I choose it say something went wrong
https://youtube.com/shorts/OCoYikZsUe0

**Comment by Natoune** [comment]
If Android Auto voice control works like the one on the phone, it should work now!

**Comment by sukabai** [comment]
I've made a test, without car stereo and it's working as expected. Will try in car next days, probably Friday and get back with feedback 
https://youtube.com/shorts/KZvNOt1Vctg

**Comment by sukabai** [comment]
I've made a test, without car stereo and it's working as expected. Will try in car next days, probably Friday and get back with feedback 
https://youtube.com/shorts/KZvNOt1Vctg

**Comment by sukabai** [comment]
Works ok now

**Comment by sukabai** [comment]
Thank you!
